- name: configure mysql component
  hosts: mysql
  become: yes
  tasks:

  - name: install mariadb server
    ansible.builtin.dnf:
      name: mariadb105-server
      state: present

  - name: start mariadb server
    ansible.builtin.service:
      name: mariadb
      state: started
      enabled: yes

  - name: set root password
    ansible.builtin.shell: |
      mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'RoboShop@1';"


  
