- name: Install Redis on Amazon Linux 2023
  hosts: redis
  become: yes

  vars:
    redis_conf: /etc/redis6/redis6.conf

  tasks:
  - name: Install Redis
    ansible.builtin.dnf:
      name: redis6
      state: present

  - name: Allow remote connections
    ansible.builtin.replace:
      path: "{{ redis_conf }}"
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: Disable protected mode
    ansible.builtin.lineinfile:
      path: "{{ redis_conf }}"
      regexp: '^protected-mode'
      line: 'protected-mode no'

  - name: Enable and start Redis
    ansible.builtin.service:
      name: redis6
      state: started
      enabled: yes



