- name: Install and Configure Redis on Amazon Linux 2023
  hosts: redis
  become: yes

  vars:
    redis_conf: /etc/redis.conf

  tasks:

  - name: Install Redis package
    ansible.builtin.dnf:
      name: redis6
      state: present

  - name: Configure bind address safely
    ansible.builtin.lineinfile:
      path: "{{ redis_conf }}"
      regexp: '^bind'
      line: 'bind 0.0.0.0 -::1'

  - name: Disable protected mode
    ansible.builtin.lineinfile:
      path: "{{ redis_conf }}"
      regexp: '^protected-mode'
      line: 'protected-mode no'

  - name: Restart and enable Redis
    ansible.builtin.service:
      name: redis6
      state: restarted
      enabled: yes




