- name: Install Redis on Amazon Linux 2023
  hosts: redis
  become: yes

  tasks:
  - name: Install EPEL repository
    ansible.builtin.dnf:
      name: epel-release
      state: present

  - name: Install Redis
    ansible.builtin.dnf:
      name: redis
      state: present

  - name: Allow remote connections
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: Disable protected mode
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: '^protected-mode'
      line: 'protected-mode no'

  - name: Enable and start Redis
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes

