- name: install redis component
  hosts: redis
  become: yes

  tasks:
    - name: install redis6
      ansible.builtin.dnf:
        name: redis6
        state: present

    - name: enable and start redis6
      ansible.builtin.service:
        name: redis6
        state: started
        enabled: yes

    - name: allow remote connections at runtime
      ansible.builtin.command: >
        redis6-cli CONFIG SET bind 0.0.0.0
      ignore_errors: yes

    - name: disable protected mode at runtime
      ansible.builtin.command: >
        redis6-cli CONFIG SET protected-mode no
      ignore_errors: yes






