- name: Install and Configure Redis on Amazon Linux 2023
  hosts: redis
  become: yes

  vars:
    redis_conf: /etc/redis.conf

  tasks:

  - name: Install Redis
    ansible.builtin.dnf:
      name: redis6
      state: present

  - name: Comment existing bind lines
    ansible.builtin.replace:
      path: "{{ redis_conf }}"
      regexp: '^bind .*'
      replace: '# \g<0>'

  - name: Add new bind configuration
    ansible.builtin.lineinfile:
      path: "{{ redis_conf }}"
      line: 'bind 0.0.0.0'
      insertafter: EOF

  - name: Disable protected mode
    ansible.builtin.lineinfile:
      path: "{{ redis_conf }}"
      regexp: '^protected-mode'
      line: 'protected-mode no'

  - name: Restart and enable Redis
    ansible.builtin.service:
      name: redis6
      state: restarted
      enabled: yes




