- name: Install and Configure Redis on Amazon Linux 2023
  hosts: redis
  become: yes

  tasks:

  - name: Install Redis package
    ansible.builtin.dnf:
      name: redis6
      state: present

  # Detect the actual config file used by the service
  - name: Get redis service config path
    ansible.builtin.shell: "systemctl cat redis6 | grep -o '/etc[^ ]*conf' | head -1"
    register: redis_conf_path
    changed_when: false

  - name: Set redis config fact
    ansible.builtin.set_fact:
      redis_conf: "{{ redis_conf_path.stdout | default('/etc/redis6/redis6.conf') }}"

  - name: Show detected redis config
    ansible.builtin.debug:
      msg: "Redis config file: {{ redis_conf }}"

  - name: Configure bind address
    ansible.builtin.lineinfile:
      path: "{{ redis_conf }}"
      regexp: '^bind'
      line: 'bind 0.0.0.0'
      create: yes

  - name: Disable protected mode
    ansible.builtin.lineinfile:
      path: "{{ redis_conf }}"
      regexp: '^protected-mode'
      line: 'protected-mode no'
      create: yes

  - name: Restart and enable Redis
    ansible.builtin.service:
      name: redis6
      state: restarted
      enabled: yes




