- name: install redis component
  hosts: redis
  become: yes

  tasks:
  - name: install redis6
    ansible.builtin.dnf:
      name: redis6
      state: present

  - name: enable and start redis6
    ansible.builtin.service:
      name: redis6
      state: started
      enabled: yes

  # 🔍 Detect actual redis config file
  - name: detect redis config path
    ansible.builtin.shell: |
      if [ -f /etc/redis/redis.conf ]; then
        echo /etc/redis/redis.conf
      elif [ -f /etc/redis6.conf ]; then
        echo /etc/redis6.conf
      elif [ -f /etc/redis.conf ]; then
        echo /etc/redis.conf
      fi
    register: redis_conf_path
    changed_when: false

  - name: set redis config path
    ansible.builtin.set_fact:
      redis_conf: "{{ redis_conf_path.stdout }}"

  - name: allow remote connections
    ansible.builtin.replace:
      path: "{{ redis_conf }}"
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
    when: redis_conf != ""

  - name: disable protected mode
    ansible.builtin.lineinfile:
      path: "{{ redis_conf }}"
      regexp: '^protected-mode'
      line: 'protected-mode no'
    when: redis_conf != ""
