- name: install redis component
  hosts: redis
  become: yes
  tasks:
  - name: refresh dnf cache
    command: dnf makecache

  - name: try installing redis
    dnf:
      name: redis
      state: present
    register: redis_install
    ignore_errors: yes

  - name: install redis6 if redis not found
    dnf:
      name: redis6
      state: present
    when: redis_install is failed



  - name: allow remote connections
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: disable protected mode
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: 'protected-mode'
      replace: 'protected-mode no'

  - name: enable and start redis
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes