- name: install redis component
  hosts: redis
  become: yes

  tasks:
  - name: install redis6
    ansible.builtin.dnf:
      name: redis6
      state: present

  - name: enable and start redis6
    ansible.builtin.service:
      name: redis6
      state: started
      enabled: yes

  - name: allow remote connections
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: disable protected mode
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: '^protected-mode'
      line: 'protected-mode no'


  - name: enable and start redis6
    ansible.builtin.service:
      name: redis6
      state: started
      enabled: yes
