- name: configure shipping component
  hosts: shipping
  become: yes
  tasks:

  - name: install maven
    ansible.builtin.dnf:
      name: maven
      state: present

  - name: install PyMySQL driver
    ansible.builtin.dnf:
      name: python3-PyMySQL
      state: present

  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory
      owner: roboshop
      group: roboshop

  - name: download shipping code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip

  - name: extract shipping code
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: build shipping package
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: rename jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app

  - name: copy shipping service
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: reload systemd
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: enable and start shipping
    ansible.builtin.service:
      name: shipping
      state: started
      enabled: yes

  # 🔽 DB SETUP (MISSING IN YOUR PLAYBOOK)

  - name: create cities database
    community.mysql.mysql_db:
      name: cities
      state: present
      login_user: root
      login_password: RoboShop@1
      login_host: localhost

  - name: create shipping DB user
    community.mysql.mysql_user:
      name: shipping
      password: RoboShop@1
      host: localhost
      priv: "cities.*:ALL"
      state: present
      login_user: root
      login_password: RoboShop@1
      login_host: localhost

  - name: verify mysql connection
    community.mysql.mysql_info:
      login_user: shipping
      login_password: RoboShop@1
      login_host: localhost
      login_db: cities



  

